const API = location.origin;
const state = { token: sessionStorage.getItem('ops_token'), refresh: sessionStorage.getItem('ops_refresh'), profile: null, page: 'overview', cache: {} };
const $ = (id) => document.getElementById(id);
const esc = (value) => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money = (value) => `$${Number(value || 0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const shortDate = (value) => value ? new Date(value).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}) : '—';
const dateTime = (value) => value ? new Date(value).toLocaleString() : '—';
const has = (permission) => state.profile?.permissions?.includes('*') || state.profile?.permissions?.includes(permission);
const hasRole = (...roles) => roles.some(role => state.profile?.roles?.some(item => item.role_key === role));

const pages = [
  ['overview','Overview','◇',()=>true], ['receipts','Receipts','▤',()=>has('receipts.read')],
  ['assignments','Assignments','◎',()=>has('receipts.update') || hasRole('receipt_editor')],
  ['support','Support access','◌',()=>has('support.approve_access') || hasRole('support_agent')],
  ['users','Users','♙',()=>has('users.read')], ['customers','Customers','▦',()=>has('users.read')],
  ['roles','Roles & permissions','⌘',()=>has('users.read')], ['audit','Audit log','◫',()=>has('audit.read')]
];

function toast(message, error=false){const node=$('toast');node.textContent=message;node.className=`toast show${error?' error':''}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.className='toast',3200)}
function authHeaders(){return state.token?{'Authorization':`Bearer ${state.token}`}:{}}
async function api(path, options={}){
  const response=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...authHeaders(),...(options.headers||{})}});
  let data={};try{data=await response.json()}catch{}
  if(response.status===401 && state.refresh && !options._retried){
    const refreshed=await fetch(`${API}/auth/refresh`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:state.refresh})});
    if(refreshed.ok){const body=await refreshed.json();saveSession(body.session);return api(path,{...options,_retried:true})}
    logout();throw new Error('Your session expired. Please sign in again.');
  }
  if(!response.ok)throw new Error(data.detail||data.message||`Request failed (${response.status})`);
  return data;
}
function saveSession(session){state.token=session?.access_token;state.refresh=session?.refresh_token||state.refresh;sessionStorage.setItem('ops_token',state.token||'');sessionStorage.setItem('ops_refresh',state.refresh||'')}
function logout(){sessionStorage.removeItem('ops_token');sessionStorage.removeItem('ops_refresh');state.token=null;state.profile=null;$('appView').classList.add('hidden');$('loginView').classList.remove('hidden')}
function modal(title, body){$('modalBody').innerHTML=`<div class="modal-head"><h3>${esc(title)}</h3><button class="modal-close" onclick="closeModal()">×</button></div><div class="modal-content">${body}</div>`;$('modal').showModal()}
window.closeModal=()=>$('modal').close();
function pageHead(title,copy,actions=''){return `<div class="page-head"><div><h3>${esc(title)}</h3><div class="muted">${esc(copy)}</div></div><div class="actions">${actions}</div></div>`}
function empty(copy){return `<div class="empty">${esc(copy)}</div>`}

async function start(){
  if(!state.token)return logout();
  try{state.profile=await api('/rbac/me');if(!state.profile.rbac_available)throw new Error('RBAC database migration has not been activated yet.');
    const operatorRoles=new Set(['platform_admin','master_user','customer_owner','support_agent','receipt_editor','auditor']);
    if(!state.profile.roles?.some(role=>operatorRoles.has(role.role_key)))throw new Error('This account uses the ReceiptAI customer app and has no operations-console role.');
    $('loginView').classList.add('hidden');$('appView').classList.remove('hidden');renderNav();await navigate('overview');
  }catch(error){logout();$('loginError').textContent=error.message}
}
function renderNav(){
  $('nav').innerHTML=pages.filter(p=>p[3]()).map(([key,label,icon])=>`<button class="nav-button ${state.page===key?'active':''}" data-page="${key}"><span class="nav-icon">${icon}</span>${label}</button>`).join('');
  $('nav').querySelectorAll('button').forEach(button=>button.onclick=()=>navigate(button.dataset.page));
  const primary=state.profile.roles?.[0]?.role_key?.replaceAll('_',' ')||'operator';
  $('operatorCard').innerHTML=`<strong>${esc(state.profile.email||'Operator')}</strong><span>${esc(primary)}</span>`;
}
async function navigate(page){
  state.page=page;renderNav();const item=pages.find(p=>p[0]===page);$('pageTitle').textContent=item?.[1]||'Operations';$('content').innerHTML='<div class="loading-panel">Loading…</div>';
  try{await ({overview:renderOverview,receipts:renderReceipts,assignments:renderAssignments,support:renderSupport,users:renderUsers,customers:renderCustomers,roles:renderRoles,audit:renderAudit}[page]||renderOverview)()}
  catch(error){$('content').innerHTML=empty(error.message);toast(error.message,true)}
}

async function getCustomers(force=false){if(!state.cache.customers||force)state.cache.customers=(await api('/rbac/customers')).customers||[];return state.cache.customers}
async function getUsers(force=false){if(!state.cache.users||force)state.cache.users=(await api('/rbac/users')).users||[];return state.cache.users}

async function renderOverview(){
  const data=await api('/rbac/overview');
  const receipts=has('receipts.read')?(await api('/receipts')).receipts.slice(0,6):[];
  $('content').innerHTML=pageHead('Workspace overview','Your authorized operational scope and current workload.')+
  `<div class="stats"><div class="stat"><span>Accessible receipts</span><strong>${data.receipts}</strong><em>verified scope</em></div><div class="stat"><span>Receipt value</span><strong>${money(data.total_spend)}</strong><em>visible records</em></div><div class="stat"><span>Open assignments</span><strong>${data.open_assignments}</strong><em>active work</em></div><div class="stat"><span>Support grants</span><strong>${data.active_support_grants}</strong><em>active access</em></div></div>`+
  `<div class="grid-2"><section class="panel"><div class="panel-head"><h4>Recent receipts</h4><button class="ghost" onclick="navigate('receipts')">View all</button></div>${receiptTable(receipts,false)}</section><section class="panel"><div class="panel-head"><h4>Access profile</h4></div><div class="panel-body"><p class="muted">Roles</p><div class="permission-list">${(data.roles||[]).map(r=>`<span class="pill purple">${esc(r.replaceAll('_',' '))}</span>`).join('')}</div><p class="muted" style="margin-top:22px">Permissions</p><div class="permission-list">${(state.profile.permissions||[]).slice(0,12).map(p=>`<span class="pill">${esc(p)}</span>`).join('')}</div></div></section></div>`;
}
function receiptTable(rows,actions=true){if(!rows.length)return empty('No receipts in your authorized scope.');return `<div class="table-wrap"><table><thead><tr><th>Receipt</th><th>Store</th><th>Purchase date</th><th>Total</th><th>Owner</th>${actions?'<th></th>':''}</tr></thead><tbody>${rows.map(r=>`<tr><td><button class="table-link" onclick="openReceipt(${Number(r.id)})">#${esc(r.id)}</button></td><td>${esc(r.store||'Unknown')}</td><td>${esc(r.date||'—')}</td><td>${money(r.total)}</td><td><span class="pill">${esc((r.user_id||'guest').slice(0,8))}</span></td>${actions?`<td><button class="secondary" onclick="openReceipt(${Number(r.id)})">Open</button></td>`:''}</tr>`).join('')}</tbody></table></div>`}
async function renderReceipts(){const rows=(await api('/receipts')).receipts||[];state.cache.receipts=rows;$('content').innerHTML=pageHead('Receipt workspace','View and correct only receipts allowed by your role.')+`<div class="toolbar"><input id="receiptSearch" placeholder="Search store, date or receipt ID" /></div><section class="panel" id="receiptResults">${receiptTable(rows)}</section>`;$('receiptSearch').oninput=e=>{const q=e.target.value.toLowerCase();const filtered=rows.filter(r=>`${r.id} ${r.store} ${r.date}`.toLowerCase().includes(q));$('receiptResults').innerHTML=receiptTable(filtered)}}
window.openReceipt=async(id)=>{try{const receipt=(state.cache.receipts||[]).find(r=>Number(r.id)===Number(id))||(await api('/receipts')).receipts.find(r=>Number(r.id)===Number(id));if(!receipt)throw new Error('Receipt is no longer accessible.');const editable=has('receipts.update');const itemEditable=has('receipts.correct_items');modal(`Receipt #${id}`,`<form id="receiptForm"><div class="form-grid"><label>Store<input name="store" value="${esc(receipt.store||'')}" ${editable?'':'disabled'} /></label><label>Purchase date<input name="date" value="${esc(receipt.date||'')}" ${editable?'':'disabled'} /></label><label>Address<input name="address" value="${esc(receipt.address||'')}" ${editable?'':'disabled'} /></label><label>Payment method<input name="payment_method" value="${esc(receipt.payment_method||'')}" ${editable?'':'disabled'} /></label><label>Transaction number<input name="transaction_number" value="${esc(receipt.transaction_number||'')}" ${editable?'':'disabled'} /></label><label>Total<input value="${esc(receipt.total||'')}" disabled /></label></div><div class="receipt-items">${(receipt.items||[]).map((item,index)=>`<div class="item-row"><label>Item<input data-field="name" data-index="${index}" value="${esc(item.name||item.item||'')}" ${itemEditable?'':'disabled'} /></label><label>Price<input data-field="price" data-index="${index}" type="number" step=".01" value="${esc(item.price??'')}" ${itemEditable?'':'disabled'} /></label><label>Category<input data-field="category" data-index="${index}" value="${esc(item.category||'')}" ${itemEditable?'':'disabled'} /></label>${itemEditable?`<button type="button" class="secondary" onclick="saveItem(${id},${index})">Save item</button>`:''}</div>`).join('')||empty('No extracted line items.')}</div>${editable?'<div class="form-actions"><button type="button" class="ghost" onclick="closeModal()">Cancel</button><button class="primary">Save receipt</button></div>':''}</form>`);if(editable)$('receiptForm').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target);const body=Object.fromEntries([...form].filter(([,v])=>String(v).trim()!==''));await api(`/receipts/${id}`,{method:'PATCH',body:JSON.stringify(body)});toast('Receipt updated');closeModal();delete state.cache.receipts;renderReceipts()}}catch(error){toast(error.message,true)}};
window.saveItem=async(receiptId,index)=>{try{const fields=[...document.querySelectorAll(`[data-index="${index}"]`)];const body={};fields.forEach(input=>{if(input.value!=='')body[input.dataset.field]=input.dataset.field==='price'?Number(input.value):input.value});await api(`/receipts/${receiptId}/items/${index}`,{method:'PATCH',body:JSON.stringify(body)});toast('Receipt item corrected')}catch(error){toast(error.message,true)}};

async function renderAssignments(){const rows=(await api('/rbac/receipt-assignments')).assignments||[];const canAssign=has('receipts.update');$('content').innerHTML=pageHead('Receipt assignments','Route correction work to a specific operator.',canAssign?'<button class="primary" onclick="assignmentModal()">Assign receipt</button>':'')+`<section class="panel">${rows.length?`<div class="table-wrap"><table><thead><tr><th>Receipt</th><th>Assignee</th><th>Permissions</th><th>Expires</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>#${esc(r.receipt_id)}</td><td>${esc(r.assignee_user_id)}</td><td>${(r.permissions||[]).map(p=>`<span class="pill">${esc(p)}</span>`).join(' ')}</td><td>${dateTime(r.expires_at)}</td><td><span class="pill ${r.revoked_at?'red':'green'}">${r.revoked_at?'Revoked':'Active'}</span></td><td>${canAssign&&!r.revoked_at?`<button class="danger" onclick="revokeAssignment('${esc(r.id)}')">Revoke</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:empty('No receipt assignments found.')}</section>`}
window.assignmentModal=async()=>{try{const users=await getUsers();const receipts=state.cache.receipts||(await api('/receipts')).receipts;modal('Assign receipt',`<form id="assignmentForm" class="stack"><label>Receipt<select name="receipt_id" required>${receipts.map(r=>`<option value="${r.id}">#${r.id} · ${esc(r.store||'Unknown')} · ${esc(r.date||'')}</option>`).join('')}</select></label><label>Operator<select name="assignee_user_id" required>${users.map(u=>`<option value="${u.id}">${esc(u.name)} · ${esc(u.email)}</option>`).join('')}</select></label><label>Expires (optional)<input name="expires_at" type="datetime-local" /></label><div class="form-actions"><button type="button" class="ghost" onclick="closeModal()">Cancel</button><button class="primary">Assign</button></div></form>`);$('assignmentForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(!data.expires_at)delete data.expires_at;else data.expires_at=new Date(data.expires_at).toISOString();data.receipt_id=Number(data.receipt_id);data.permissions=['receipts.read','receipts.correct_items'];await api('/rbac/receipt-assignments',{method:'POST',body:JSON.stringify(data)});closeModal();toast('Receipt assigned');renderAssignments()}}catch(error){toast(error.message,true)}};
window.revokeAssignment=async id=>{if(!confirm('Revoke this receipt assignment?'))return;try{await api(`/rbac/receipt-assignments/${id}`,{method:'DELETE'});toast('Assignment revoked');renderAssignments()}catch(error){toast(error.message,true)}};

async function renderSupport(){const rows=(await api('/rbac/support-grants')).grants||[];const canApprove=has('support.approve_access');$('content').innerHTML=pageHead('Support access','Time-limited, case-based access with a complete audit trail.',canApprove?'<button class="primary" onclick="supportModal()">Grant access</button>':'')+`<section class="panel">${rows.length?`<div class="table-wrap"><table><thead><tr><th>Case</th><th>Support user</th><th>Scope</th><th>Expires</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.case_id)}</strong><div class="muted">${esc(r.reason)}</div></td><td>${esc(r.support_user_id)}</td><td>${r.receipt_id?`Receipt #${esc(r.receipt_id)}`:`Customer ${esc(r.customer_id)}`}</td><td>${dateTime(r.expires_at)}</td><td><span class="pill ${r.revoked_at?'red':'green'}">${r.revoked_at?'Revoked':'Active'}</span></td><td>${canApprove&&!r.revoked_at?`<button class="danger" onclick="revokeGrant('${esc(r.id)}')">Revoke</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:empty('No support grants in this scope.')}</section>`}
window.supportModal=async()=>{try{const customers=await getCustomers();const users=await getUsers();const support=users.filter(u=>u.roles?.some(r=>r.role_key==='support_agent'));modal('Grant support access',`<form id="supportForm" class="stack"><label>Support operator<select name="support_user_id" required>${support.map(u=>`<option value="${u.id}">${esc(u.name)} · ${esc(u.email)}</option>`).join('')}</select></label><label>Customer<select name="customer_id" required>${customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label>Receipt ID (optional; limits access to one receipt)<input name="receipt_id" type="number" /></label><label>Case ID<input name="case_id" required placeholder="SUP-1042" /></label><label>Reason<textarea name="reason" required placeholder="Describe why access is required"></textarea></label><label>Expires<input name="expires_at" type="datetime-local" required /></label><div class="form-actions"><button type="button" class="ghost" onclick="closeModal()">Cancel</button><button class="primary">Approve access</button></div></form>`);$('supportForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.expires_at=new Date(data.expires_at).toISOString();if(data.receipt_id)data.receipt_id=Number(data.receipt_id);else delete data.receipt_id;data.permissions=['receipts.read','receipts.correct_items'];await api('/rbac/support-grants',{method:'POST',body:JSON.stringify(data)});closeModal();toast('Support access granted');renderSupport()}}catch(error){toast(error.message,true)}};
window.revokeGrant=async id=>{if(!confirm('Revoke this support access now?'))return;try{await api(`/rbac/support-grants/${id}/revoke`,{method:'POST'});toast('Support access revoked');renderSupport()}catch(error){toast(error.message,true)}};

async function renderUsers(){const users=await getUsers(true);$('content').innerHTML=pageHead('Operator directory','Create accounts, assign roles and control operator access.',has('users.manage')?'<button class="primary" onclick="userModal()">New operator</button>':'')+`<section class="panel">${users.length?`<div class="table-wrap"><table><thead><tr><th>User</th><th>Roles</th><th>Last sign-in</th><th>Status</th><th></th></tr></thead><tbody>${users.map(u=>`<tr><td><strong>${esc(u.name)}</strong><div class="muted">${esc(u.email)}</div></td><td>${(u.roles||[]).filter(r=>r.active).map(r=>`<span class="pill purple">${esc(r.role_key.replaceAll('_',' '))}</span>`).join(' ')||'—'}</td><td>${dateTime(u.last_sign_in_at)}</td><td><span class="pill ${u.banned_until?'red':'green'}">${u.banned_until?'Inactive':'Active'}</span></td><td>${has('users.manage')?`<button class="secondary" onclick="roleModal('${u.id}')">Assign role</button> <button class="${u.banned_until?'secondary':'danger'}" onclick="toggleUser('${u.id}',${u.banned_until?'true':'false'})">${u.banned_until?'Activate':'Deactivate'}</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:empty('No operators found.')}</section>`}
window.userModal=async()=>{const customers=await getCustomers();const roles=(await api('/rbac/roles')).roles;modal('Create operator',`<form id="userForm" class="form-grid"><label>Name<input name="name" required /></label><label>Email<input name="email" type="email" required /></label><label>Temporary password<input name="password" type="password" minlength="8" required /><small class="muted">At least 8 characters with uppercase, lowercase and a special character.</small></label><label>Role<select name="role_key">${roles.map(r=>`<option value="${r.role_key}">${esc(r.display_name)}</option>`).join('')}</select></label><label class="wide">Customer scope<select name="customer_id"><option value="">No customer scope — assign individual receipts</option>${customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select><small class="muted">Receipt Editors may be created without a customer and receive individual assignments later.</small></label><p id="operatorFormError" class="form-error wide"></p><div class="form-actions wide"><button type="button" class="ghost" onclick="closeModal()">Cancel</button><button class="primary">Create operator</button></div></form>`);$('userForm').onsubmit=async e=>{e.preventDefault();const error=$('operatorFormError');error.textContent='';const submit=e.target.querySelector('button[type="submit"],button.primary');submit.disabled=true;try{const data=Object.fromEntries(new FormData(e.target));if(!data.customer_id)delete data.customer_id;await api('/rbac/users',{method:'POST',body:JSON.stringify(data)});closeModal();toast('Operator created');renderUsers()}catch(problem){error.textContent=problem.message;toast(problem.message,true)}finally{submit.disabled=false}}};
window.roleModal=async userId=>{const customers=await getCustomers();const roles=(await api('/rbac/roles')).roles;modal('Assign role',`<form id="roleForm" class="stack"><label>Role<select name="role_key">${roles.map(r=>`<option value="${r.role_key}">${esc(r.display_name)}</option>`).join('')}</select></label><label>Customer scope<select name="customer_id"><option value="">Global / not applicable</option>${customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><div class="form-actions"><button type="button" class="ghost" onclick="closeModal()">Cancel</button><button class="primary">Assign</button></div></form>`);$('roleForm').onsubmit=async e=>{e.preventDefault();const data={user_id:userId,...Object.fromEntries(new FormData(e.target))};if(!data.customer_id)delete data.customer_id;await api('/rbac/user-roles',{method:'POST',body:JSON.stringify(data)});closeModal();toast('Role assigned');renderUsers()}};
window.toggleUser=async(id,active)=>{if(!confirm(`${active?'Activate':'Deactivate'} this operator?`))return;try{await api(`/rbac/users/${id}/status`,{method:'PATCH',body:JSON.stringify({active})});toast(`Operator ${active?'activated':'deactivated'}`);renderUsers()}catch(error){toast(error.message,true)}};

async function renderCustomers(){const rows=await getCustomers(true);$('content').innerHTML=pageHead('Customers','Organization workspaces and isolated receipt scopes.',hasRole('platform_admin')?'<button class="primary" onclick="customerModal()">New customer</button>':'')+`<section class="panel">${rows.length?`<div class="table-wrap"><table><thead><tr><th>Customer</th><th>Type</th><th>Identifier</th><th>Created</th></tr></thead><tbody>${rows.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td><span class="pill">${esc(c.kind)}</span></td><td>${esc(c.slug||c.id)}</td><td>${shortDate(c.created_at)}</td></tr>`).join('')}</tbody></table></div>`:empty('No customer workspaces in your scope.')}</section>`}
window.customerModal=()=>{modal('Create customer',`<form id="customerForm" class="stack"><label>Organization name<input name="name" required /></label><label>URL slug<input name="slug" placeholder="north-store-group" /></label><div class="form-actions"><button type="button" class="ghost" onclick="closeModal()">Cancel</button><button class="primary">Create</button></div></form>`);$('customerForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(!data.slug)delete data.slug;await api('/rbac/customers',{method:'POST',body:JSON.stringify(data)});closeModal();toast('Customer created');renderCustomers()}};

async function renderRoles(){const roles=(await api('/rbac/roles')).roles||[];$('content').innerHTML=pageHead('Roles & permissions','Review the exact capabilities granted to each operator group.')+`<section class="panel">${roles.map(r=>`<article class="role-card"><div class="page-head" style="margin:0"><div><h4>${esc(r.display_name)}</h4><div class="muted">${esc(r.description)}</div></div>${hasRole('platform_admin')&&r.role_key!=='platform_admin'?`<button class="secondary" onclick="permissionModal('${esc(r.role_key)}')">Edit permissions</button>`:''}</div><div class="permission-list">${(r.permissions||[]).map(p=>`<span class="pill">${esc(p)}</span>`).join('')}</div></article>`).join('')}</section>`;state.cache.roles=roles}
window.permissionModal=roleKey=>{const role=state.cache.roles.find(r=>r.role_key===roleKey);const all=[...new Set(state.cache.roles.flatMap(r=>r.permissions||[]))].sort();modal(`Permissions · ${role.display_name}`,`<form id="permissionForm"><div class="permission-list">${all.map(p=>`<label class="pill"><input style="width:auto" type="checkbox" name="permission" value="${esc(p)}" ${(role.permissions||[]).includes(p)?'checked':''} /> ${esc(p)}</label>`).join('')}</div><div class="form-actions"><button type="button" class="ghost" onclick="closeModal()">Cancel</button><button class="primary">Save permissions</button></div></form>`);$('permissionForm').onsubmit=async e=>{e.preventDefault();const permissions=[...e.target.querySelectorAll('input:checked')].map(x=>x.value);await api(`/rbac/roles/${roleKey}/permissions`,{method:'PUT',body:JSON.stringify({permissions})});closeModal();toast('Role permissions updated');renderRoles()}};

async function renderAudit(){const customer=state.profile.customer_ids?.[0];const query=customer&&!hasRole('platform_admin','master_user')?`?customer_id=${encodeURIComponent(customer)}&limit=200`:'?limit=200';const rows=(await api(`/rbac/audit${query}`)).events||[];$('content').innerHTML=pageHead('Audit trail','Security-sensitive changes recorded across your authorized scope.')+`<section class="panel">${rows.length?`<div class="table-wrap"><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Resource</th><th>Reason</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${dateTime(r.created_at)}</td><td>${esc((r.actor_user_id||'system').slice(0,10))}</td><td><span class="pill purple">${esc(r.action)}</span></td><td>${esc(r.resource_type)} ${esc(r.resource_id||'')}</td><td>${esc(r.reason||'—')}</td></tr>`).join('')}</tbody></table></div>`:empty('No audit events in this scope.')}</section>`}

$('loginForm').onsubmit=async event=>{event.preventDefault();$('loginError').textContent='';try{const body=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('loginEmail').value,password:$('loginPassword').value,name:''})});const data=await body.json();if(!body.ok)throw new Error(data.detail||'Sign in failed');saveSession(data.session);await start()}catch(error){$('loginError').textContent=error.message}};
$('logoutBtn').onclick=logout;$('refreshBtn').onclick=()=>{state.cache={};navigate(state.page)};$('menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
window.navigate=navigate;
start();
